### ISSUE TITLE
Trailing slash check is superfluous

### ISSUE THREAD

**Issue by daneah** [ithaka/apiron#15]
**Is your feature request related to a problem? Please describe.**
The trailing slash check was originally intended to address a problem that can't be solved within this package. Endpoint owners make the decision (conscious or otherwise) to support a trailing slash or not, and by checking for a trailing slash this package is perhaps overly-opinionated on an issue that has no actual standard in REST. This ultimately produces a fair amount of noise in large projects that is arguably providing little value.

**Describe the solution you'd like**
Remove the trailing slash checks altogether.

**Describe alternatives you've considered**
The only alternatives here would be "deal with it" or add `check_for_trailing_slash=False` to everything. Neither of these seem particularly wonderful.

**Comment by daneah** [comment]
@jefftriplett as you previously suffered from the noise produced by this check, what are your thoughts here?

**Comment by jefftriplett** [comment]
@daneah I didn't find `check_for_trailing_slash` to be particularly useful since about 50% of the APIs I work with do not have a trailing slash. I assumed that it was needed for a bug or nitpick that y'all ran into previously. I'd prefer to have it not be noisy by default because I can't think of a time when I'd find that feature to be useful.

**Comment by daneah** [comment]
@jefftriplett beautiful, thanks for the feedback! We'll rip this out for the next release.
